"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { CheckCircle2, FileText, FileUp, RefreshCw, Sparkles, Trash2, UploadCloud, X, AlertCircle } from "lucide-react";
import { addManualTopic, deleteDocument, fetchDocumentDetail, fetchDocuments, reprocessDocument, uploadDocument, type DocumentDetailResponse, type DocumentListItem } from "@/lib/api";
import { Card } from "@/components/ui/card";

const ACCEPT = ".pdf,.docx,.txt,.png,.jpg,.jpeg";
const supported = new Set(["pdf", "docx", "txt", "png", "jpg", "jpeg"]);
const enter = { hidden: { opacity: 0, y: 10 }, show: { opacity: 1, y: 0, transition: { duration: .22 } } };
const size = (bytes: number) => bytes < 1024 * 1024 ? `${Math.max(1, Math.round(bytes / 1024))} KB` : `${(bytes / 1024 / 1024).toFixed(1)} MB`;

export function DocumentManager() {
  const [documents, setDocuments] = useState<DocumentListItem[]>([]); const [selected, setSelected] = useState<DocumentDetailResponse | null>(null);
  const [queue, setQueue] = useState<File[]>([]); const [progress, setProgress] = useState<Record<string, number>>({}); const [busy, setBusy] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null); const [dragging, setDragging] = useState(false); const input = useRef<HTMLInputElement>(null);
  const [initializing, setInitializing] = useState(false);
  const load = async (id?: string) => { const items = await fetchDocuments(); setDocuments(items); const chosen = id ?? selected?.id ?? items[0]?.id; if (chosen) setSelected(await fetchDocumentDetail(chosen)); else setSelected(null); };
  useEffect(() => { load().catch((e: Error) => setError(e.message)); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  const addFiles = (files: FileList | File[]) => { const valid = Array.from(files).filter(f => supported.has(f.name.split(".").pop()?.toLowerCase() ?? "")); if (valid.length !== Array.from(files).length) setError("Only PDF, DOCX, TXT, PNG, JPG, and JPEG files are supported."); setQueue(current => [...current, ...valid].slice(0, 12)); };
  const uploadAll = async () => { if (!queue.length) return; setError(null); setNotice(null); const firstTwin = documents.length === 0; setInitializing(firstTwin); let latest: string | undefined; for (const file of queue) { const key = `${file.name}-${file.lastModified}`; setBusy(key); try { const result = await uploadDocument(file, undefined, undefined, value => setProgress(p => ({ ...p, [key]: value }))); latest = result.document_id; } catch (e) { setError(e instanceof Error ? e.message : "Upload failed"); break; } } setQueue([]); setBusy(null); setInitializing(false); if (latest) { setNotice("Analysis complete — your Digital Twin has been updated."); await load(latest); } };
  const processAction = async (id: string, action: "retry" | "delete") => { setBusy(id); setError(null); try { if (action === "retry") { await reprocessDocument(id); setNotice("Document reprocessed successfully."); await load(id); } else { await deleteDocument(id); setNotice("Document and its extracted data were removed."); await load(); } } catch (e) { setError(e instanceof Error ? e.message : "Action failed"); } finally { setBusy(null); } };
  const addTopic = async () => { if (!selected) return; const name = window.prompt("Add a topic to this Digital Twin"); if (!name?.trim()) return; try { const detail = await addManualTopic(selected.id, name.trim()); setSelected(detail); await load(detail.id); setNotice("Topic added to the Digital Twin."); } catch (e) { setError(e instanceof Error ? e.message : "Could not add topic"); } };
  const selectedRow = useMemo(() => documents.find(d => d.id === selected?.id), [documents, selected]);
  return <><AnimatePresence>{initializing && <motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-50 grid place-items-center bg-[#08090d]/85 p-5 backdrop-blur-md"><motion.div initial={{scale:.98,y:8}} animate={{scale:1,y:0}} className="surface w-full max-w-md rounded-3xl p-7"><p className="eyebrow">Digital Twin Initialization</p><h3 className="mt-3 text-2xl font-semibold">Your learning system is waking up.</h3><div className="mt-6 space-y-3">{["Scanning pages…", "Extracting modules…", "Finding deadlines…", "Building knowledge graph…", "Creating memory profile…", "Estimating study workload…"].map((step,index) => <motion.div key={step} initial={{opacity:.25,x:-5}} animate={{opacity:1,x:0}} transition={{delay:index*.15,duration:.2}} className="flex items-center gap-3 text-sm text-zinc-300"><span className="size-2 rounded-full bg-violet-300 shadow-[0_0_12px_rgba(196,181,253,.8)]"/>{step}</motion.div>)}</div></motion.div></motion.div>}</AnimatePresence><motion.div initial="hidden" animate="show" variants={{ show: { transition: { staggerChildren: .06 } } }} className="grid gap-4 xl:grid-cols-[1.18fr_.82fr]">
    <motion.div variants={enter} className="space-y-4"><Card className="p-5"><p className="eyebrow">Document center</p><div className="mt-2 flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-2xl font-semibold">Give your twin something real to learn from.</h2><p className="mt-2 text-sm text-zinc-500">Each document becomes structured courses, topics, deadlines, and knowledge state.</p></div><span className="text-xs text-zinc-500">PDF · DOCX · TXT · PNG · JPG</span></div>
      <div onDragOver={e => { e.preventDefault(); setDragging(true); }} onDragLeave={() => setDragging(false)} onDrop={e => { e.preventDefault(); setDragging(false); addFiles(e.dataTransfer.files); }} onClick={() => input.current?.click()} className={`mt-5 cursor-pointer rounded-2xl border border-dashed p-6 transition duration-200 ${dragging ? "border-violet-300 bg-violet-400/10" : "border-white/15 bg-white/[.025] hover:border-violet-300/60 hover:bg-white/[.045]"}`}><div className="flex items-center gap-4"><div className="grid size-11 place-items-center rounded-xl bg-violet-400/10 text-violet-200"><UploadCloud size={21}/></div><div><p className="font-medium">Drop files here or browse</p><p className="mt-1 text-sm text-zinc-500">Select multiple files — ECHO processes them one at a time.</p></div></div><input ref={input} onChange={e => e.target.files && addFiles(e.target.files)} accept={ACCEPT} multiple type="file" className="hidden"/></div>
      {queue.length > 0 && <div className="mt-4 space-y-2">{queue.map(file => { const key = `${file.name}-${file.lastModified}`; return <div key={key} className="rounded-xl bg-white/[.035] px-3 py-2.5"><div className="flex items-center justify-between text-sm"><span className="truncate">{file.name}</span><button onClick={() => setQueue(q => q.filter(item => item !== file))} className="text-zinc-500 hover:text-white"><X size={15}/></button></div>{busy === key && <div className="mt-2 h-1 overflow-hidden rounded-full bg-white/10"><motion.div className="h-full bg-violet-400" animate={{ width: `${progress[key] ?? 8}%` }} transition={{ duration: .2 }}/></div>}</div>; })}<button onClick={uploadAll} disabled={!!busy} className="mt-2 inline-flex items-center gap-2 rounded-xl bg-white px-4 py-2.5 text-sm font-medium text-zinc-950 transition duration-200 hover:shadow-[0_0_24px_rgba(196,181,253,.35)] active:scale-[.98] disabled:opacity-60"><Sparkles size={16}/>{busy ? "Processing document…" : `Analyze ${queue.length} file${queue.length > 1 ? "s" : ""}`}</button></div>}
      <AnimatePresence>{notice && <motion.div initial={{ opacity: 0, y: -5 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} className="mt-4 flex gap-2 rounded-xl border border-emerald-400/20 bg-emerald-400/10 p-3 text-sm text-emerald-200"><CheckCircle2 size={18}/>{notice}</motion.div>}{error && <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="mt-4 flex gap-2 rounded-xl border border-rose-400/20 bg-rose-400/10 p-3 text-sm text-rose-200"><AlertCircle size={18}/>{error}</motion.div>}</AnimatePresence></Card>
      <Card className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-white/[.035] text-xs uppercase tracking-wide text-zinc-500"><tr><th className="px-4 py-3">Document</th><th>Course</th><th>Size</th><th>Status</th><th>Uploaded</th><th/></tr></thead><tbody>{documents.map(doc => <tr key={doc.id} onClick={() => fetchDocumentDetail(doc.id).then(setSelected)} className={`cursor-pointer border-t border-white/[.06] transition hover:bg-white/[.035] ${selected?.id === doc.id ? "bg-violet-400/[.06]" : ""}`}><td className="px-4 py-3 font-medium">{doc.filename}</td><td className="text-zinc-400">{doc.course ?? "Detecting…"}</td><td className="text-zinc-500">{size(doc.size_bytes)}</td><td><span className={doc.status === "ready" ? "text-emerald-300" : doc.status === "failed" ? "text-rose-300" : "text-violet-300"}>{doc.status}</span></td><td className="text-zinc-500">{new Date(doc.uploaded_date).toLocaleDateString()}</td><td className="px-4"><div className="flex gap-2"><button aria-label="Retry" onClick={e => { e.stopPropagation(); processAction(doc.id, "retry"); }} className="rounded-lg p-1.5 text-zinc-400 transition hover:bg-white/10 hover:text-white"><RefreshCw size={15}/></button><button aria-label="Delete" onClick={e => { e.stopPropagation(); processAction(doc.id, "delete"); }} className="rounded-lg p-1.5 text-zinc-400 transition hover:bg-rose-400/10 hover:text-rose-200"><Trash2 size={15}/></button></div></td></tr>)}{documents.length === 0 && <tr><td colSpan={6} className="px-4 py-12 text-center text-zinc-500">Your analyzed learning materials will appear here.</td></tr>}</tbody></table></div></Card></motion.div>
    <motion.aside variants={enter}><Card className="sticky top-5 p-5"><div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-xl bg-violet-400/10 text-violet-200"><FileText size={18}/></div><div><p className="font-medium">Document intelligence</p><p className="text-xs text-zinc-500">{selected?.filename ?? "Select a document"}</p></div></div>{selected ? <div className="mt-5 space-y-4">{selected.error_message && <div className="rounded-xl bg-rose-500/10 p-3 text-sm text-rose-200">{selected.error_message}</div>}<section><p className="text-xs font-medium uppercase tracking-wider text-zinc-500">Academic structure</p><div className="mt-2 grid gap-2 text-sm"><p><span className="text-zinc-500">Course:</span> {selected.analysis.course_name ?? "Not detected"}</p><p><span className="text-zinc-500">Code:</span> {selected.analysis.subject_code ?? "—"}</p><p><span className="text-zinc-500">Instructor:</span> {selected.analysis.instructor ?? "—"}</p><p><span className="text-zinc-500">Term:</span> {[selected.analysis.semester, selected.analysis.academic_year].filter(Boolean).join(" · ") || "—"}</p></div></section><section><div className="flex items-center justify-between"><p className="text-xs font-medium uppercase tracking-wider text-zinc-500">Topic hierarchy</p><button onClick={addTopic} className="text-xs text-violet-300 hover:text-violet-100">+ Add topic</button></div><div className="mt-2 space-y-2">{selected.analysis.topic_hierarchy.map(module => <div key={module.name} className="rounded-xl bg-white/[.035] p-3"><p className="text-sm font-medium">{module.name}</p><p className="mt-1 text-xs leading-5 text-zinc-400">{module.topics.join(" · ") || "No child topics detected"}</p></div>)}{!selected.analysis.topic_hierarchy.length && <p className="text-sm text-zinc-500">Topics will appear after analysis.</p>}</div></section><section><p className="text-xs font-medium uppercase tracking-wider text-zinc-500">Timeline extracted</p><div className="mt-2 space-y-2">{selected.analysis.timeline_events.map(event => <div key={`${event.event}-${event.date}`} className="rounded-xl bg-white/[.035] p-3 text-sm"><p>{event.event}</p><p className="mt-1 text-xs text-violet-300">{event.date} · {event.priority}</p></div>)}{!selected.analysis.timeline_events.length && <p className="text-sm text-zinc-500">No dated academic events found.</p>}</div></section></div> : <div className="mt-8 rounded-xl bg-white/[.025] p-5 text-sm text-zinc-500">Choose a document to inspect its extracted Digital Twin data.</div>}</Card></motion.aside>
  </motion.div></>;
}
