"use client";

import { useEffect, useState } from "react";
import { motion } from "framer-motion";
import { Calculator, Clock3, Moon, TrendingUp } from "lucide-react";
import { simulateScenario, type SimulationPrediction, type SimulationRequest } from "@/lib/api";
import { Card } from "@/components/ui/card";

const defaults: SimulationRequest = { study_hours_per_day: 3, sleep_hours: 7.5, attendance: 85, days_skipped: 0, revision_frequency: 3, exam_date: null };
const labels: Array<[keyof SimulationRequest, string, number, number, number]> = [["study_hours_per_day", "Study hours / day", 0, 12, .5], ["sleep_hours", "Sleep hours", 3, 12, .5], ["attendance", "Attendance", 0, 100, 1], ["days_skipped", "Days skipped", 0, 14, 1], ["revision_frequency", "Revisions / week", 0, 14, 1]];

export function SimulatorPanel() {
  const [scenario, setScenario] = useState<SimulationRequest>(defaults); const [prediction, setPrediction] = useState<SimulationPrediction | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { const timer = window.setTimeout(() => simulateScenario(scenario).then(setPrediction).catch((e: Error) => setError(e.message)), 180); return () => window.clearTimeout(timer); }, [scenario]);
  const change = (key: keyof SimulationRequest, value: number | string | null) => setScenario(old => ({ ...old, [key]: value }));
  return <motion.div initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={{duration:.22}} className="grid gap-4 xl:grid-cols-[.95fr_1.05fr]"><Card className="p-5"><div className="flex items-center gap-2"><Calculator className="text-violet-300" size={18}/><div><p className="font-medium">What-if simulator</p><p className="text-xs text-zinc-500">Every change updates the forecast.</p></div></div><div className="mt-6 space-y-5">{labels.map(([key,label,min,max,step]) => <label key={key} className="block"><div className="flex justify-between text-sm"><span className="text-zinc-400">{label}</span><span>{scenario[key]}</span></div><input value={scenario[key] as number} onChange={e => change(key, Number(e.target.value))} type="range" min={min} max={max} step={step} className="mt-2 w-full accent-violet-400"/></label>)}<label className="block text-sm"><span className="text-zinc-400">Exam date (optional)</span><input value={scenario.exam_date ?? ""} onChange={e => change("exam_date", e.target.value || null)} type="date" className="mt-2 w-full rounded-xl border border-white/10 bg-white/[.03] px-3 py-2.5 outline-none"/></label></div></Card><Card className="p-5"><div className="flex items-center gap-2"><TrendingUp className="text-violet-300" size={18}/><p className="font-medium">Live outcome forecast</p></div>{error ? <p className="mt-4 text-sm text-rose-300">{error}</p> : prediction ? <motion.div key={`${prediction.expected_exam_score}-${prediction.stress}`} initial={{opacity:.4,scale:.985}} animate={{opacity:1,scale:1}} transition={{duration:.2}} className="mt-5"><div className="grid gap-3 sm:grid-cols-2">{[["Expected exam score",prediction.expected_exam_score,"text-emerald-300"],["Academic health",prediction.academic_health,"text-violet-200"],["Memory retention",prediction.memory_retention,"text-violet-200"],["Stress",prediction.stress,"text-rose-300"],["Confidence",prediction.confidence,"text-violet-200"],["Study load",prediction.recommended_study_load,"text-white"]].map(([label,value,color]) => <div key={String(label)} className="rounded-2xl bg-white/[.035] p-4"><p className="text-xs text-zinc-500">{label}</p><p className={`mt-1 text-3xl font-semibold ${color}`}>{Number(value).toFixed(1)}{label === "Study load" ? " h" : "%"}</p></div>)}</div><div className="mt-4 rounded-2xl bg-violet-500/10 p-4"><div className="flex items-center gap-2 text-violet-100"><Moon size={16}/><p className="text-sm font-medium">Why this changed</p></div><p className="mt-2 text-sm leading-6 text-zinc-200">{prediction.explanation}</p></div></motion.div> : <div className="mt-6 h-44 animate-pulse rounded-2xl bg-white/[.03]"/>}</Card></motion.div>;
}
