"use client";

import { useEffect, useMemo, useState } from "react";
import { motion } from "framer-motion";
import { BrainCircuit, CalendarClock, HeartPulse, Network, Sparkles } from "lucide-react";
import { fetchTwin, type TwinResponse } from "@/lib/api";
import { Card } from "@/components/ui/card";

const title = (key: string) => key.replace(/_/g, " ").replace(/\b\w/g, c => c.toUpperCase());
const signalColor = (v: number, inverse = false) => (inverse ? v > 60 : v < 50) ? "text-rose-300" : v > 72 ? "text-emerald-300" : "text-violet-200";

export function TwinView() {
  const [data, setData] = useState<TwinResponse | null>(null); const [selected, setSelected] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { fetchTwin().then(setData).catch((e: Error) => setError(e.message)); }, []);
  const selectedNode = useMemo(() => data?.knowledge_graph.nodes.find(n => n.id === selected), [data, selected]);
  if (error) return <Card className="border-rose-500/30 bg-rose-500/10 p-6 text-rose-100">Could not load your twin: {error}</Card>;
  if (!data) return <div className="grid gap-4 md:grid-cols-3">{[1,2,3,4,5,6].map(x => <Card key={x} className="h-32 animate-pulse bg-white/[.03]"/>)}</div>;
  return <motion.div initial="hidden" animate="show" variants={{ hidden: {}, show: { transition: { staggerChildren: .05 } } }} className="space-y-4">
    <motion.div variants={{hidden:{opacity:0,y:8},show:{opacity:1,y:0}}}><Card className="overflow-hidden p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow">Digital Twin</p><h2 className="mt-2 text-2xl font-semibold">Your learning system, in motion.</h2><p className="mt-2 text-sm text-zinc-500">Every signal is recalculated from your documents, topics, revisions, and deadlines.</p></div><div className="rounded-xl bg-violet-400/10 px-3 py-2 text-sm text-violet-100">Health {data.academic_health.toFixed(0)}%</div></div><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{Object.entries(data.learning_dna).map(([key, value]) => <div key={key} className="rounded-2xl bg-white/[.035] p-3"><p className="text-xs text-zinc-500">{title(key)}</p><motion.p key={value} initial={{opacity:.3,y:4}} animate={{opacity:1,y:0}} transition={{duration:.22}} className={`mt-1 text-2xl font-semibold ${signalColor(value, key === "burnout_risk")}`}>{value.toFixed(0)}%</motion.p></div>)}</div></Card></motion.div>
    <div className="grid gap-4 xl:grid-cols-[1.25fr_.75fr]"><Card className="p-5"><div className="flex items-center gap-2"><Network size={18} className="text-violet-300"/><p className="font-medium">Knowledge graph</p><span className="ml-auto text-xs text-zinc-500">Select a topic</span></div><div className="relative mt-5 min-h-[330px] overflow-hidden rounded-2xl border border-white/[.06] bg-[#0a0b10] p-4"><svg className="pointer-events-none absolute inset-0 h-full w-full opacity-40">{data.knowledge_graph.edges.map((_, i) => <line key={i} x1="12%" y1={`${15 + (i % 6) * 13}%`} x2="48%" y2={`${15 + ((i + 2) % 6) * 13}%`} stroke="#8b5cf6" strokeWidth="1"/>)}</svg><div className="relative grid gap-2 md:grid-cols-2">{data.knowledge_graph.nodes.filter(n => n.type !== "student").map(node => <button key={node.id} onClick={() => setSelected(node.id)} className={`rounded-xl border p-3 text-left transition duration-200 hover:scale-[1.02] ${node.type === "topic" ? (node.value ?? 50) < 50 ? "border-rose-400/30 bg-rose-500/10 shadow-[0_0_18px_rgba(244,63,94,.14)]" : "border-emerald-400/25 bg-emerald-500/[.07] shadow-[0_0_18px_rgba(52,211,153,.10)]" : "border-violet-400/25 bg-violet-400/[.08]"}`}><p className="text-sm font-medium">{node.label}</p><p className="mt-1 text-xs text-zinc-400">{node.type} {node.value != null ? `· ${node.value.toFixed(0)}%` : ""}</p></button>)}</div></div></Card><Card className="p-5"><div className="flex items-center gap-2"><BrainCircuit size={18} className="text-violet-300"/><p className="font-medium">Topic intelligence</p></div>{selectedNode ? <div className="mt-5 space-y-4"><div className="rounded-2xl bg-white/[.035] p-4"><p className="text-lg font-semibold">{selectedNode.label}</p><p className="mt-1 text-sm text-zinc-500">{selectedNode.type} in your knowledge graph</p><p className={`mt-4 text-3xl font-semibold ${signalColor(selectedNode.value ?? 0)}`}>{selectedNode.value?.toFixed(0) ?? "—"}%</p><p className="text-xs text-zinc-500">Current confidence</p></div><div className="text-sm text-zinc-400"><p>Recommended study time: <span className="text-white">{Math.max(20, Math.round(110 - (selectedNode.value ?? 50)))} min</span></p><p className="mt-2">Revision history: <span className="text-white">Derived from topic activity</span></p></div></div> : <p className="mt-8 text-sm text-zinc-500">Choose any topic node to see its confidence, revision state, and suggested study time.</p>}</Card></div>
    <div className="grid gap-4 xl:grid-cols-2"><Card className="p-5"><div className="flex items-center gap-2"><BrainCircuit size={18} className="text-violet-300"/><p className="font-medium">Memory decay radar</p></div><div className="mt-5 space-y-3">{data.memory_decay.map(item => <div key={item.topic}><div className="flex justify-between text-sm"><span>{item.topic}</span><span className="text-rose-200">{item.today.toFixed(0)}% → {item.two_weeks.toFixed(0)}%</span></div><div className="mt-2 flex h-2 overflow-hidden rounded-full bg-white/10">{[item.today,item.tomorrow,item.three_days,item.one_week,item.two_weeks].map((value,i) => <motion.span key={i} initial={{width:0}} animate={{width:`${value/5}%`}} transition={{duration:.25,delay:i*.03}} className={`h-full ${value < 50 ? "bg-rose-400" : "bg-violet-400"}`}/>)}</div><p className="mt-1 text-xs text-zinc-500">Today · Tomorrow · 3 days · 1 week · 2 weeks</p></div>)}{!data.memory_decay.length && <p className="text-sm text-zinc-500">Upload a syllabus to create memory projections.</p>}</div></Card><Card className="p-5"><div className="flex items-center gap-2"><CalendarClock size={18} className="text-violet-300"/><p className="font-medium">Future timeline</p></div><div className="mt-5 space-y-3">{data.future_timeline.map((item,i) => <div key={`${item.label}-${i}`} className="border-l border-violet-400/40 pl-4"><p className="text-sm font-medium">{item.label}</p><p className="mt-1 text-xs text-violet-200">{item.date}</p><p className="mt-1 text-xs text-zinc-500">{item.detail}</p></div>)}{!data.future_timeline.length && <p className="text-sm text-zinc-500">No future events are available yet.</p>}</div></Card></div>
    <Card className="p-5"><div className="flex items-center gap-2"><HeartPulse size={18} className="text-violet-300"/><p className="font-medium">How Academic Health is calculated</p></div><div className="mt-4 grid gap-3 md:grid-cols-4">{data.academic_health_factors.map(factor => <div key={factor.label} className="rounded-xl bg-white/[.035] p-3"><p className="text-sm">{factor.label}</p><p className="mt-1 text-2xl font-semibold">{factor.value.toFixed(0)}%</p><p className="mt-1 text-xs text-zinc-500">{factor.detail}</p></div>)}</div></Card>
  </motion.div>;
}
